name       : ldb
version    : 1.1.29
release    : 1
source     :
    - https://www.samba.org/ftp/ldb/ldb-1.1.29.tar.gz : 59d84f9a5b799f519ba7b2685bb46f5a26f1bbf05b7a144b2f5e017d01d80f97
license    : GPL-3.0
component  : programming
summary    : ldb is a LDAP-like embedded database
description: |
    ldb is a LDAP-like embedded database
builddeps  :
    - pkgconfig(popt)
    - pkgconfig(talloc)
    - pkgconfig(tdb)
    - pkgconfig(tevent)
setup      : |
    %configure --with-modulesdir=/usr/lib64
build      : |
    %make
install    : |
    %make_install
