name       : ldb
version    : 2.2.0
release    : 17
source     :
    - https://www.samba.org/ftp/ldb/ldb-2.2.0.tar.gz : 134bb51769709af59f30bf468e454d1377a8096acd4e80dcb42fd264f558bd5f
license    : LGPL-3.0-or-later
component  : programming
summary    : ldb is a LDAP-like embedded database
description: |
    ldb is a LDAP-like embedded database
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(popt)
    - pkgconfig(tdb)
    - pkgconfig(tevent)
setup      : |
    %configure \
      --with-modulesdir=%libdir%/ldb/modules \
      --with-privatelibdir=%libdir%/ldb \
      --without-ldb-lmdb \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
