name       : ldb
version    : 1.4.7
release    : 10
source     :
    - https://www.samba.org/ftp/ldb/ldb-1.4.7.tar.gz : 90032bf738a5aea0c350f8d40f1df7f46932df0b3f61e7100df5f1c3975cf944
license    : LGPL-3.0-or-later
component  : programming
summary    : ldb is a LDAP-like embedded database
description: |
    ldb is a LDAP-like embedded database
builddeps  :
    - pkgconfig(cmocka)
    - pkgconfig(popt)
    - pkgconfig(tdb)
    - pkgconfig(tevent)
setup      : | 
    %configure \
      --with-modulesdir=%libdir%/ldb/modules \
      --with-privatelibdir=%libdir%/ldb \
      --without-ldb-lmdb \
      --bundled-libraries=NONE \
      --builtin-libraries=replace \
      --disable-rpath-install \
      --disable-python
build      : |
    %make
install    : |
    %make_install
